# 这是一个示例配置文件，请复制为application-dev.yaml并填入真实信息
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hmdp?useSSL=false&serverTimezone=UTC
    username: your_username
    password: your_password
  redis:
    host: localhost
    port: 6379
    password: your_redis_password
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s